# Generated by Django 4.0.5 on 2022-06-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejka1', models.IntegerField(blank=True, null=True)),
                ('kolejka2', models.IntegerField(blank=True, null=True)),
                ('kolejka3', models.IntegerField(blank=True, null=True)),
                ('kolejka4', models.IntegerField(blank=True, null=True)),
                ('kolejka5', models.IntegerField(blank=True, null=True)),
                ('kolejka6', models.IntegerField(blank=True, null=True)),
                ('kolejka7', models.IntegerField(blank=True, null=True)),
                ('kolejka8', models.IntegerField(blank=True, null=True)),
                ('kolejka9', models.IntegerField(blank=True, null=True)),
                ('kolejka10', models.IntegerField(blank=True, null=True)),
                ('kolejka11', models.IntegerField(blank=True, null=True)),
                ('kolejka12', models.IntegerField(blank=True, null=True)),
                ('kolejka13', models.IntegerField(blank=True, null=True)),
                ('kolejka14', models.IntegerField(blank=True, null=True)),
                ('kolejka15', models.IntegerField(blank=True, null=True)),
                ('kolejka16', models.IntegerField(blank=True, null=True)),
                ('kolejka17', models.IntegerField(blank=True, null=True)),
                ('kolejka18', models.IntegerField(blank=True, null=True)),
                ('kolejka19', models.IntegerField(blank=True, null=True)),
                ('kolejka20', models.IntegerField(blank=True, null=True)),
                ('kolejka21', models.IntegerField(blank=True, null=True)),
                ('kolejka22', models.IntegerField(blank=True, null=True)),
                ('kolejka23', models.IntegerField(blank=True, null=True)),
                ('kolejka24', models.IntegerField(blank=True, null=True)),
                ('kolejka25', models.IntegerField(blank=True, null=True)),
                ('kolejka26', models.IntegerField(blank=True, null=True)),
                ('kolejka27', models.IntegerField(blank=True, null=True)),
                ('kolejka28', models.IntegerField(blank=True, null=True)),
                ('kolejka29', models.IntegerField(blank=True, null=True)),
                ('kolejka30', models.IntegerField(blank=True, null=True)),
                ('kolejka31', models.IntegerField(blank=True, null=True)),
                ('kolejka32', models.IntegerField(blank=True, null=True)),
                ('kolejka33', models.IntegerField(blank=True, null=True)),
                ('kolejka34', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
