# Generated by Django 4.0.5 on 2022-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_footercode_headercode_title_delete_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterCode',
        ),
        migrations.DeleteModel(
            name='HeaderCode',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='kolejka',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
