# Generated by Django 4.0.5 on 2022-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_footercode_delete_headercode_delete_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kolejka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
