# Generated by Django 4.0.5 on 2022-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_kolejka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kolejka',
            field=models.CharField(blank=True, default='Kolejka', max_length=100, null=True),
        ),
    ]
