# Generated by Django 4.0.5 on 2022-06-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejka', models.CharField(blank=True, default='Kolejka', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='kolejka',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
    ]
