# Generated by Django 4.0.5 on 2022-06-14 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_post_kolejka_alter_kolejka_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kolejka',
            name='user',
        ),
        migrations.AddField(
            model_name='kolejka',
            name='user',
            field=models.ManyToManyField(related_name='kolejka', to=settings.AUTH_USER_MODEL),
        ),
    ]
