# Generated by Django 4.0.5 on 2022-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_post_options_vote_color_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surnname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
