# Generated by Django 4.0.5 on 2022-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ankieta_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolejka',
            name='name',
            field=models.CharField(choices=[('Kolejka 1', 'Kolejka 1'), ('Kolejka 2', 'Kolejka 2'), ('Kolejka 3', 'Kolejka 3'), ('Kolejka 4', 'Kolejka 4'), ('Kolejka 5', 'Kolejka 5'), ('Kolejka 6', 'Kolejka 6'), ('Kolejka 7', 'Kolejka 7'), ('Kolejka 8', 'Kolejka 8'), ('Kolejka 9', 'Kolejka 9'), ('Kolejka 10', 'Kolejka 10'), ('Kolejka 11', 'Kolejka 11'), ('Kolejka 12', 'Kolejka 12'), ('Kolejka 13', 'Kolejka 13'), ('Kolejka 14', 'Kolejka 14'), ('Kolejka 15', 'Kolejka 15'), ('Kolejka 16', 'Kolejka 16'), ('Kolejka 17', 'Kolejka 17'), ('Kolejka 18', 'Kolejka 18'), ('Kolejka 19', 'Kolejka 19'), ('Kolejka 20', 'Kolejka 20'), ('Kolejka 21', 'Kolejka 21'), ('Kolejka 22', 'Kolejka 22'), ('Kolejka 23', 'Kolejka 23'), ('Kolejka 24', 'Kolejka 24'), ('Kolejka 25', 'Kolejka 25'), ('Kolejka 26', 'Kolejka 26'), ('Kolejka 27', 'Kolejka 27'), ('Kolejka 28', 'Kolejka 28'), ('Kolejka 29', 'Kolejka 29'), ('Kolejka 30', 'Kolejka 30'), ('Kolejka 31', 'Kolejka 31'), ('Kolejka 32', 'Kolejka 32'), ('Kolejka 33', 'Kolejka 33'), ('Kolejka 34', 'Kolejka 34'), ('Dodatkowe wydarzenie', 'Dodatkowe Wydarzenie')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='kolejka',
            field=models.CharField(blank=True, choices=[('Kolejka 1', 'Kolejka 1'), ('Kolejka 2', 'Kolejka 2'), ('Kolejka 3', 'Kolejka 3'), ('Kolejka 4', 'Kolejka 4'), ('Kolejka 5', 'Kolejka 5'), ('Kolejka 6', 'Kolejka 6'), ('Kolejka 7', 'Kolejka 7'), ('Kolejka 8', 'Kolejka 8'), ('Kolejka 9', 'Kolejka 9'), ('Kolejka 10', 'Kolejka 10'), ('Kolejka 11', 'Kolejka 11'), ('Kolejka 12', 'Kolejka 12'), ('Kolejka 13', 'Kolejka 13'), ('Kolejka 14', 'Kolejka 14'), ('Kolejka 15', 'Kolejka 15'), ('Kolejka 16', 'Kolejka 16'), ('Kolejka 17', 'Kolejka 17'), ('Kolejka 18', 'Kolejka 18'), ('Kolejka 19', 'Kolejka 19'), ('Kolejka 20', 'Kolejka 20'), ('Kolejka 21', 'Kolejka 21'), ('Kolejka 22', 'Kolejka 22'), ('Kolejka 23', 'Kolejka 23'), ('Kolejka 24', 'Kolejka 24'), ('Kolejka 25', 'Kolejka 25'), ('Kolejka 26', 'Kolejka 26'), ('Kolejka 27', 'Kolejka 27'), ('Kolejka 28', 'Kolejka 28'), ('Kolejka 29', 'Kolejka 29'), ('Kolejka 30', 'Kolejka 30'), ('Kolejka 31', 'Kolejka 31'), ('Kolejka 32', 'Kolejka 32'), ('Kolejka 33', 'Kolejka 33'), ('Kolejka 34', 'Kolejka 34'), ('Dodatkowe wydarzenie', 'Dodatkowe Wydarzenie')], max_length=200, null=True),
        ),
    ]
