# Generated by Django 4.0.5 on 2022-07-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_comment_post_info_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.comment'),
        ),
    ]
