# Generated by Django 4.0.5 on 2022-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_remove_info_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='comment',
            field=models.ManyToManyField(related_name='comments', to='info.comment'),
        ),
    ]
