# Generated by Django 4.0.5 on 2022-07-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_comment_author_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='info.info'),
            preserve_default=False,
        ),
    ]
