# Generated by Django 4.0.5 on 2022-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
